import Image from 'next/image';
import Link from 'next/link';

import styles from './HomepageNonProfit.module.scss';

export default function HomepageNonProfit() {
  return (
    <div className={styles.cta}>
          <div className="wp-block-media-text has-media-on-the-right is-stacked-on-mobile white-image-right">
            <div className="wp-block-media-text__content">
              <h2 className="wp-block-heading"> The Academy&apos;s <span className='gold'>Nonprofit</span></h2>
              <p>Cal Maritime Corporation is a nonprofit, self-supporting entity. Unlike the university, we receive no state funding. Every dollar generated by our activities goes back to the Cal Poly Maritime Academy, providing vital resources to the campus community.</p>
              <p>
                <Link href="https://maritime-archive.calpoly.edu/corporation/about/mission.html" target='_blank' rel='noopener noreferrer' title="Mission, Vision and Values">
                    Mission, Vision and Values
                </Link>
              </p>
            </div>
            <figure className="wp-block-media-text__media">
              <Image
                src="/home/cal-maritime-student-center-nonprofit-campus-support.jpg"
                width={980}
                height={630}
                alt="Cal Maritime student center building with modern glass design and outdoor gathering area, representing the nonprofit mission of Cal Maritime Corporation to support cadets and the campus community."
                layout="responsive"
              />
            </figure>
          </div>
    </div>
  );
}